# _config.yml
# This file contains only the basic page settings.
title: "My Mission and Plans"            # Page title
theme: minima                             # Chosen theme for a minimalistic design
